### ISSUE TITLE
Loading a precomputed de Bruijn graph requires `--node-length` parameter despite contrary info in the documentation

### ISSUE THREAD

**Issue by tmaklin** [algbio/themisto#13]
With Themisto v2.1.0, running the commands
```
themisto build -k 31 -i example.fasta -o index --temp-dir tmp --no-colors
themisto build --load-dbg --index-prefix index -i example.fasta --temp-dir tmp
```
produces the error `Error: Option ‘node-length’ has no value`. According to the documentation of `--load-dbg`, the node length parameter should not be required here.

**Comment by jnalanko** [comment]
Fixed in commit 9959404. The value of --node-length is now ignored if the DBG is loaded from disk, and a warning is printed.
