### ISSUE TITLE
*.fa suffix is not supported

### ISSUE THREAD

**Issue by karel-brinda** [algbio/themisto#2]
```
0.0250 Mon Sep 14 15:03:09 2020 Themisto-v0.2.0-1-gd8e44f5
Runtime error: Unknown file format: small.fa
```

**Comment by tmaklin** [comment]
I've added support for recognizing files with a .fa suffix as fasta files in pull request #4 

The changes are not yet merged to the main branch. In the meanwhile you can work around the issue by changing the suffixes of your input files from ".fa" to ".fasta" if you'd like to.
