### ISSUE TITLE
Themisto hangs with invalid input format

### ISSUE THREAD

**Issue by AntonBogun** [algbio/themisto#29]
Reproduction:
- Repeat steps here https://github.com/algbio/themisto/issues/28#issue-1868676686 but remove the newline at the end of the last line, or remove more lines, for example being left with
```
@Example
CTTTGTGCGCTTCACTCATGTTCCACGCCACCATCAACAGCAGGGCAGCCATGGCGGAAAGCGGCAGCCAGGAGAGCAGCGGTGCCAGTACCAGCAGGGC
```
- When running the pseudoalignment with the same command, the stderr output should be
```
50.1910 Mon Aug 28 02:54:09 2023 Themisto-v3.1.3
50.3850 Mon Aug 28 02:54:09 2023 Maximum k-mer length (size of the de Bruijn graph node labels): 32
51.7450 Mon Aug 28 02:54:09 2023 Starting
51.8230 Mon Aug 28 02:54:09 2023 Loading the index
75.9620 Mon Aug 28 02:54:09 2023 sdsl coloring structure loaded
76.0230 Mon Aug 28 02:54:09 2023 Aligning example.fastq (writing output to out.txt)
Input: 0.000000 Mbase/s
```
With the last line remaining there indefinitely.

**Comment by jnalanko** [comment]
Thanks for the report, I'll look into getting this fixed as soon as I have time.

**Comment by jnalanko** [comment]
At commit aeeecef, Themisto now correctly crashes on this file, printing: `Runtime error: FASTQ file example.fastq ended unexpectedly.`
