### ISSUE TITLE
option to print genome labels from index?

### ISSUE THREAD

**Issue by clb21565** [algbio/themisto#33]
hi there-- might be just a bit thick here, but, is there a way to print which reference genomes (e.g., ENA identifiers) went into an index? 

alternatively-- if not-- do you have the metadata that went into building these indices https://zenodo.org/records/6656911 ?

**Comment by jnalanko** [comment]
Hi, the unfortunately metadata is not stored in the index. This is something we could change in a future version. @tmaklin might be able to answer where the metadata for that dataset is.

**Comment by clb21565** [comment]
thanks!
