### ISSUE TITLE
Recommended usage for metatranscriptomics 

### ISSUE THREAD

**Issue by jolespin** [algbio/themisto#41]
I have about 1M CDS sequences I would like to use as a reference.  Can themisto handle this type of data? If so, are there any recommended settings to adjust? Also, how does this compare to Salmon?

**Comment by jnalanko** [comment]
Hi,

Themisto should have no problem scaling to that amount of data. The default parameters should be fine, that is, k = 31 and pseudoalignment threshold 1.

Unlike Salmon, Themisto is not a full transcript quantification pipeline, but just the first part of it. In Salmon, transcript quantification is done in two phases: (1) mapping reads to reference transcripts, (2) estimating transcript abundances using a statistical model based on the output of stage 1. Themisto does only stage 1. The output is essentially a compatibility matrix between reads and transcripts. For the second phase, we recommend [mSWEEP](https://github.com/probic/mSWEEP), which works directly on Themisto output. However, it's mainly designed for the use case of bacterial strain deconvolution, and does not take into account some things that Salmon does, for example, GC content and positional bias. If your goal is transcript quantification, Salmon likely gives more accurate results. If you just want a compatibility matrix for other purposes, Themisto will provide you just that.

**Comment by jolespin** [comment]
Thank you!  I really appreciate the insight.
